import MainLayout from '@/layouts/MainLayout'
import TextContainer from '@/layouts/TextContainer'
import Head from 'next/head'
import Link from 'next/link'

const Terms = () => {
    return (
        <MainLayout>
            <Head>
                <meta name="description" content="Mavie terms and conditions." />
                <meta property="og:title" content="MaVie Global / Terms & Conditions" />
                <meta property="og:url" content="https://mavie.global/terms-and-conditions" />
                <meta property="og:image" content="https://mavie.global/assets/images/terms-og.png" />
            </Head>
            <TextContainer amount={16}>
                <section className='max-w-[90%] lg:max-w-[920px] flex flex-col justify-center items-center min-h-screen my-48 leading-snug relative'>
                    <h2 className='text-5xl text-center italic text-main-gradient font-normal'>Independent Distributor <span className='bg-main-gradient text-transparent bg-clip-text'>Terms</span> and <span className='bg-main-gradient text-transparent bg-clip-text'>Conditions.</span></h2>
                    <div className='text-left'>
                        <p className='my-6 italic'>Last update: April 2023</p>
                        <p>This Terms and Conditions govern the business relationship between an Affiliate Marketing Company MAVIE and you. The MAVIE platform, is available at the direct web link backoffice.mavie.global (hereinafter: &ldquo;site&rdquo;), is managed by MAVIElab LTD, Tortola, BRITISH VIRGIN ISLANDS, BC No: 2097992.</p>
                        <p>Please read these Terms carefully before using the services described herein and make sure you understand everything.</p>
                        <p>You expressly agree and acknowledge that you have read these Terms and agree to comply with and be bound by all of these Terms as a requirement of receiving a referral link. If at any time you do not agree with any part of these Terms, you agree to cease any further promoting activities, in which case you agree that any activity that transpired prior to the date of such termination shall be governed in full by these Terms.</p>
                        <p>Please also review Privacy Policy for information about how we collect, use and share information collected from you.</p>
                        <p className='mt-6'><span className='underline'>By registering within the MAVIE platform and perform any business with MAVIE you agree with the following statement:</span></p>
                        <p>I am of legal age in the state of my residency. I agree that I am an independent contractor responsible for determining my own business activities and not an agent or employee of the MAVIE, I am responsible for the payment of all federal and state self-employment taxes and any other tax including sales tax that may be required under federal, state or regulating taxing agency. I understand that this position does not constitute the sale of a franchise or of a distributorship and except for the license fee for the use of the Back Office software there is no enrolment fee required for me to participate as an Independent Distributor of the COMPANY MAVIE. I further acknowledge and understand that the purchase of product is optional and is not required of me in order to participate as an Independent Distributor of the COMPANY.</p>
                        <p>I agree that as an MAVIE, (also referred to as COMPANY) Independent Distributor (also referred to as ID), I shall place primary emphasis upon the promotion and support for the stated goals of the COMPANY and the solicitation of non-ID individuals, businesses and organizations as customers. In presenting COMPANY&rsquo;s stated vision and mission I agree that such presentations shall be strictly according to the following format and that I will be terminated as an ID if I fail to do so.</p>
                        <p>MAVIE may amend this Terms and Conditions at any time by reasonable notice, including without limitation by posting revised terms on its website<Link href='https://www.backoffice.mavie.global' className='underline'>https://www.backoffice.mavie.global</Link>, which amended terms and conditions shall be binding upon you. If you do not agree with the amended Terms and Conditions, you can stop using the services provided by MAVIE. Any form of further use of the software maintained and enabled by MAVIE on the website <Link href='https://www.backoffice.mavie.global' className='underline'>https://www.backoffice.mavie.global</Link> shall be considered as your consent to the amendments of these general conditions. If you continue to use MAVIE&apos;s services or products after the change of this Terms and Conditions, you cannot rely on the fact that you are not bound by changes because you did not expressly agree to them.</p>
                        <p>A. In each presentation given by the ID the prospect shall be directly informed that no enrollment fee will be charged by the COMPANY to become an ID of the COMPANY.</p>
                        <p>B. I have carefully read, understood and agree to comply with the COMPANY&rsquo;s Terms and Conditions and Policies and Procedures. I further agree and understand that the COMPANY&rsquo;s Policies and Procedures are a binding part of this agreement. I understand that I must be in good standing and not in violation of any of the terms of this agreement in order to be eligible to receive any bonuses or commissions for the COMPANY. The continuation of my COMPANY Independent Distributorship or my acceptance of bonuses or commissions shall constitute my acceptance of the Terms and Conditions, the Policies and Procedures and any and all amendments pertaining to both.</p>
                        <p>C. In order to maintain a viable marketing structure and to comply with the changes to federal, state and local laws and economic conditions, the COMPANY may provide additional Terms and Conditions for IDs from time to time, as well as to modify its ID compensation program in the Booklet and Policies and Procedures. Such additional Terms and Conditions, Policies and Procedures and Booklet modifications and all changes thereto, shall become a binding part of this Agreement upon publication on the official COMPANY website or other official COMPANY publications.</p>
                        <p>D. I understand that I must verify that my enrollees are adults of the legal age and able-bodied with legal capacity in their state of residency. I also agree that I will not make any claims, statements, or representations about the COMPANY&rsquo;s products that are not found on the COMPANY&rsquo;s websites or official marketing materials or are not specifically approved by the COMPANY (MAVIE Marketing Guidelines). I agree to indemnify the COMPANY and hold it harmless in the event I make any such unapproved statements that result in government investigation, government or private litigation, claims, regulatory action, or any other adverse event relating to the COMPANY or its products.</p>
                        <p>E. I understand that my position can be inherited or bequeathed, but cannot be transferred or assigned during my lifetime without written consent of the COMPANY. The transfer of a position is an exception and is generally allowed in special cases due to medical, social or other objective inability to continue performing the activity of an ID.</p>
                        <p>F. This Agreement shall be in effect upon its receipt and acceptance by the COMPANY either in written form, by mail or fax transmission or through the COMPANY&rsquo;s website by clicking the Terms and Conditions tab to confirm agreement.</p>
                        <p>G. I am responsible for supervising and supporting the IDs I refer or enroll into the program and in my commissionable down-lines. I agree to maintain monthly communication and support to these IDs in my commissionable down-lines by the way of any of the following or combination thereof: Personal contact, telephone communication, written communication and attendance at ID meetings.</p>
                        <p>H. As an ID of the COMPANY, I will be provided with obligatory Promo Materials and Marketing Guidelines to help me in my capacity as an ID. COMPANY provides the following fulfillment to its IDs: Optional promotional materials fulfilled Commissions are payable to IDs according to the current Compensation Plan which is incorporated in the Booklet. COMPANY provided one year of web-based back-office administration to all IDs until end of April 2023. With registration I am entitled to a 30 days free trial period, during this trial period I may access Back Office features.<span>&nbsp;</span>After trial period expire company reserves the right to charge a fee for using the Back Office in a form of a compensation for the monthly renewal fee in accordance with the respective price list of license fees for the use of the Back Office software published on the page <Link href='https://www.backoffice.mavie.global' className='underline'>https://www.backoffice.mavie.global</Link></p>
                        <p>I. I will not make false, misleading or disparaging statements about the COMPANY, its employees or founders, the compensation plan, ID positions or the COMPANY mission and vision. Display of commission checks, the making of income projections and use of income testimonials to prospective IDs is strictly prohibited. I will conduct myself as an ID in a courteous, fair and ethical manner.</p>
                        <p>J. Change of original enroller is not permitted. ID and customer lists and names are owned by the COMPANY and may never be used for any commercial or business purpose without prior written consent of the COMPANY.</p>
                        <p>K. I understand that any return of product or missing payments and fraud in my down-line or customer base may result in a charge back against commissions or bonuses paid to me by the COMPANY.</p>
                        <p>L. I authorize the COMPANY to use my name, photograph, personal story and/or likeness in advertising or promotional materials and waive all claims for remuneration for such use.</p>
                        <p>M. I agree that I will be solely responsible for paying expenses incurred by myself, including but not limited to travel, food, lodging, secretarial office, telephone, cell phone and other expenses.</p>
                        <p>N. I give permission to the company to contact me by email or text messaging for reasons including, but not limited to COMPANY announcements, bonus programs and promotions, changes in policy, etc.</p>
                        <p>O. I understand that the company may charge me a check fee of USDT 5 for any payment made to me by company check or by wire transfer or by direct deposit.</p>
                        <p>P. I understand and agree that I will not solicit another MAVIE Independent Distributor or entity to join another network marketing opportunity offered by another company during the term of my MAVIE Independent Distributorship and for a period of one year after. Violation of this company policy may result in immediate termination. In addition, I may be subject to injunctive relief including possible civil penalties and monetary damages for engaging in such conduct. In such a case, I expressly agree that all possible overdue and non-overdue obligations of the company to me cease and I waive them.</p>
                        <p>Q. I agree not to use the COMPANY name, logo, pictures, trademarks or any of the COMPANY&rsquo;s published written content to optimize any other website position in a search engine. I further understand that doing any of the above may cause financial harm to the COMPANY which may result in me being required to pay damages to the COMPANY for such actions and may also result in termination of my status as an ID of the COMPANY.</p>
                        <p>R. I understand and agree that I will not market or promote any outside service or product to any other COMPANY IDs. These include but are not limited to internet capture pages, and sales leads. It is further understood that in the course of my status as an ID of the COMPANY, I may produce marketing tools to assist my downline organization to grow their COMPANY Independent Distributorship. In doing so, I agree that such marketing tools must first be approved by the COMPANY in writing and I will not charge for any such marketing tools at any time. Further to this, I understand that although I am allowed to conduct independent training events for the COMPANY, I may not charge an admission fee for such events without a written consent by the COMPANY.</p>
                        <p>S. I understand that if I fail to comply with the terms of this agreement or Policies and Procedures of the COMPANY or any part of this agreement, the COMPANY, at its discretion, may terminate my Independent Distributorship or impose upon me other disciplinary action, including but not limited to, forfeiture of bonuses and commission, loss of all or part of my down-line marketing organization or customer base list. If I am in breach, default or violation of the agreement at termination, I shall not be entitled to receive any further bonuses or commissions, whether or not the sales of such bonuses or commissions have been completed. If this agreement is terminated for any reason, I will forever lose my rights as an ID, including rights to my down-line marketing organization and customer base list, and rights to compensation pursuant to the COMPANY&rsquo;s Marketing and Compensation Plan. If I wish to disassociate myself with the COMPANY and cancel my Independent Distributorship, I may not be eligible to rejoin the company for a period of 12 (twelve) months.</p>
                        <p>T. I understand that MAVIE provides software for the transparent management of your sales activities, non-misleading promotional material and other support in the implementation of your sales. In no case is MAVIE a seller of products offered on the market using the sales platform developed by MAVIE. As a distributor, MAVIE enters into various distribution relationships with business partners who offer products suitable for distribution through the MAVIE platform. In doing so, MAVIE cannot guarantee the operation of these products, be responsible for legal or material defects in the products, problems in delivery, fulfilment or other warranty claims. Any such claim must be addressed directly to the seller.</p>
                        <p>U. This Agreement is governed under the Laws of British Virgin Islands. In the event that a dispute hereunder arises which cannot be resolved in the normal course, the following dispute resolution procedures shall be followed:</p>
                        <p>Ombudsman: first level disputes are resolved by the external Ombudsman, who is appointed by MAVIE. Rules for resolving first level disputes are governed by the Ombudsman&rsquo;s Procedure Guidelines, published on MAVIE&rsquo;s webpage.</p>
                        <p>Arbitration: second level disputes are resolved by binding arbitration in accordance with the Rules of the Arbitration of the International Chamber of Commerce. The arbitration will be heard and determined by a three-member panel, with one member selected by each party and the third (who will chair the panel) selected by the two party-appointed members. The place of arbitration shall be Ljubljana, the proceeding shall be in Slovenian Language. The arbitration panel, as applicable, will apply Laws of British Virgin Islands and the provisions of these Terms, will determine any dispute according to the Laws of British Virgin Islands and facts based upon the record and no other basis, and will issue a reasoned award.</p>
                        <p>V. The term of this agreement is one year (subject to prior cancellation as provided in the Terms and Conditions and Policies and Procedures). If I fail to annually renew my MAVIE Independent Distributorship, or if it is cancelled or terminated for any reason, I understand that I will permanently lose all rights as an ID. I shall not be eligible to sell the COMPANY&rsquo;s products and/or services, nor shall I be eligible to receive royalties, bonuses or other income resulting for the activities of my former down-line sales organization or customer base list. In the event of cancellation, termination or nonrenewal, I waive all rights I have, including but not limited to property rights, to my former down-line organization or customer base list and customer base list and to any bonuses, commissions or other remuneration derived through the sale sand other activities of my former down-line organization and customer base list. The COMPANY reserves the right to terminate all Distributor Agreements upon 30 days notice if the COMPANY elects to: (1) cease business operations; (2) dissolve as a business entity; or (3) terminate distribution of its products and/or services via direct selling channels. IDs MAY CANCEL THIS AGREEMENT AT ANY TIME, AND FOR ANY REASON, UPON WRITTEN NOTICE TO THE COMPANY.</p>
                        <p>W. I understand that failure to comply with the above COMPANY Terms and Conditions and Policies and Procedures may result in the termination of Agreement and/or the COMPANY&rsquo;s Terms and Conditions and Policies and Procedures, the COMPANY may suspend my ID status and any payments due to me may be escrowed until final resolution has been achieved. I acknowledge that in the event of my violation of this Agreement and/or the COMPANY&rsquo;s Terms and Conditions and/or Policies and Procedures, my ID rights may be terminated without further commission or payments of any kind.</p>
                        <p>X. I agree to indemnify and hold the COMPANY, its directors, officers or employees harmless from any and all claims, damages or expenses (including attorney fees) that may arise out of my actions or conduct in violation of this Agreement.</p>
                        <p>Y. I acknowledge the COMPANY&rsquo;S Compensation Program is based on current products and is subject to change without notice.</p>
                        <h3 className='font-bold mt-8'>Definitions:</h3>
                        <p><span className='underline'>The following definitions govern the meanings of the capitalized terms used in this Agreement:</span></p>
                        <p>&ldquo;Compensation plan&rdquo; governs the payments and bonuses, compensation program and referral award plan of Independent Distributors and is published on the link <Link href='https://www.backoffice.mavie.global' className='underline'>https://www.backoffice.mavie.global</Link> under the resources section.</p>
                        <p>&ldquo;Customer or enrollees&rdquo; shall mean (i) an entity with its headquarters in the Territory (defined below), and persons with their residence in the Territory and (ii) with MAVIE&rsquo;s prior written permission, an entity that is a subsidiary of a Customer, where the sales decision regarding the Product is made for the entity by the Customer.</p>
                        <p>&ldquo;Documentation&rdquo; shall mean the user manual, if any, and specifications, if any, for the Product.</p>
                        <p>&ldquo;KYC Process&rdquo; shall mean a user identification process to ensure that identity of each user is appropriately verified. It is not only a legal requirement to assess and monitor risks, KYC is a fundamental practice to protect the integrity of MAVIE and its users from fraud and other actions which could result in reputational, operational and other forms of risks to which MAVIE and its users are exposed.</p>
                        <p>&ldquo;Full user&rdquo; shall mean a Independent Distributor that agrees with the currently valid MAVIE Terms and Conditions, valid Back Office, and thus have the ability to use the site and the MAVIE account in its full capacity.</p>
                        <p>&ldquo;Trialing user&rdquo; shall mean an Independent Distributor that agrees with the currently valid MAVIE Terms and Conditions,, during 30 days trial period of Back Office. &ldquo;Registered User&rdquo; shall mean an Independent Distributor that agrees with the currently valid MAVIE Terms and Conditions, whose trial period has expired and has no valid Back Office.</p>
                        <p>&ldquo;Customer&rdquo; shall mean any person who has purchased a product or service through the MAVIE platform.</p>
                        <p>&ldquo;Products&rdquo; are those listed in &ldquo;Promo Materials and MAVIE Marketing Guidelines&rdquo;.</p>
                        <p>&ldquo;MAVIE Marketing Guidelines&rdquo; and &ldquo;Promo Materials&rdquo; are published on the link backoffice.mavie.global .</p>
                        <p>&ldquo;Platform&rdquo; shall mean MAVIE&rsquo;s Back Office platform.</p>
                        <p>&ldquo;Independent Distributor&rdquo; a business entity or a person that acquires a referral link, Promo Guidelines and Promo Materials for the purpose of promoting MAVIE&rsquo;s Products.</p>
                        <p>&ldquo;Sale&rdquo; shall mean when each of these occurs: Customer executes an Order, MAVIE receives the Order from Independent Distributor and MAVIE accepts the Order. Independent Distributor has an overview over the sales made via referral link in its profile.</p>
                        <p>&ldquo;Territory&rdquo; shall mean the countries where activities are not explicitly permitted are considered prohibited. In any case, it is expressly prohibited to engage in any activity or sell products in the following countries: USA, BVI, UAE, SI. (except sales to foreign residents).</p>
                        <p>&ldquo;Free Trial&rdquo; shall mean a free period of 30 days during which you can use the Back Office software or other MAVIE products without a license fee. If you register on MAVIE website for a free trial, MAVIE will make one or more free subscription services available to you on a trial basis free of charge until the earlier of (a) the end of the free trial period for which you registered to use the Back Office software (s), or (b) the start date of any payable services ordered by you or (c) termination by Company in its sole discretion due to breach of this Terms and Conditions.</p>
                        <h3 className='font-bold mt-8'>MAVIE Policies and Procedures</h3>
                        <p><span className='underline'>Policies and Procedures, The Compensation Plan Booklet, and the Terms and Conditions are Incorporated into Distributor Agreement:</span></p>
                        <p>These Policies and Procedures as presented here and as amended from time to time at the sole discretion of MAVIE, (hereafter &ldquo;MAVIE&rdquo; or the &ldquo;COMPANY&rdquo;), are incorporated into, and form an integral part of, the MAVIE Distributor Agreement, Compensation Plan Booklet and Terms and Conditions. Throughout these Policies and Procedures, when the term &ldquo;Agreement&rdquo; is used, it collectively refers to the MAVIE Policies and Procedures, The MAVIE Compensation Plan Booklet and the MAVIE Terms and Conditions.</p>
                        <p>It is the responsibility of each Independent Distributor to read, understand, adhere to, and ensure that he or she is aware of and operating under the most current version of these Policies and Procedures. When enrolling a new Independent Distributor, it is the responsibility of the enrolling Independent Distributor to provide the most current version of these Policies and Procedures, the MAVIE Terms and Conditions and the MAVIE Marketing and Compensation Plan Booklet to the applicant prior to his or her execution of the Distributor Agreement. MAVIE reserves the right to change these Policies and Procedures, Terms and Conditions, Compensation Plan Booklet and Marketing Policy at any time.</p>
                        <h3 className='font-bold mt-8'>Ethics</h3>
                        <p>The COMPANY conducts business in an ethical and credible manner and requires its Independent Distributors to deal ethically with their customers, with each other and with the COMPANY. The COMPANY permits no unethical or illegal activity and will intercede when such behaviour may exist, and the COMPANY reserves the right to use its best judgment in deciding whether certain Independent Distributor activities are unethical. Furthermore, the COMPANY may use its own discretion in determining the appropriate course of action. If the COMPANY determines that unethical activities may exist, then it reserves the right to suspend or terminate Independent Distributor status, including but not limited to all commissions and payments of any kind. Under no circumstances is an Independent Distributor who is terminated for unethical or illegal activity entitled to a refund of their renewal fee, nor are they entitled to sell or transfer their position.</p>
                        <p className='my-4 underline'>Examples of unethical behaviour include but are not limited to the following:</p>
                        <p>A. Making any false or misleading remarks, statements, innuendos or rumors that may disparage the COMPANY, its products or services, its compensation plan, its employees, its founders or another COMPANY Independent Distributor.</p>
                        <p>B. Making any claim regarding the COMPANY&rsquo;s products that are not found on the COMPANY&rsquo;s current websites or official, current marketing material.</p>
                        <p>C. Making unapproved income claims or revealing the amount of income you are or have received through the COMPANY or other network marketing opportunities that you may or may not have been involved in currently or previously.</p>
                        <p>D. Directly or indirectly disclosing any information in your back office to a third party other than an official COMPANY authorized employee for the purpose of assisting you with a specific issue that is related to your MAVIE Independent Distributorship.</p>
                        <p>E. Use any of the information in your back office or activity report in a manner to influence another MAVIE Independent Distributor to alter their relationship with the Company in any way.</p>
                        <p>F. Use the information in your back office or activity report to compete with the COMPANY in any way.</p>
                        <p>G. Providing, selling or revealing any customer lists and/or their contact information that appears in your activity report or downline report to a third party. This includes the customer lists and/or their contact information that belongs to the COMPANY or appears in any other Independent Distributor&rsquo;s activity report or downline report.</p>
                        <p>H. Directly or indirectly disclosing the password or other access code to your back office or activity report</p>
                        <p>I. Use of another person&rsquo;s credit card without express written permission.</p>
                        <p>J. Forging any signature on any document.</p>
                        <p>K. Any unauthorized use of the COMPANY&rsquo;s name, logos, photos, videos, trademarks or copyrighted material in any way or fashion.</p>
                        <p>L. Violation of any state or federal laws or regulations.</p>
                        <p>M. Competing with the COMPANY&rsquo;s products or services directly or indirectly through association with another business or through your own personal efforts.</p>
                        <p>N. Aggressive or abusive language, behaviour or treatment or any inappropriate behaviour toward any COMPANY employee, founder or another COMPANY Independent Distributor.</p>
                        <p>O. Unjustified resale of the COMPANY&apos;s products, retention and unjustified fundraising or transfer of funds raised from purchases, payments for participation in courses or other services sold by the company to persons other than the COMPANY.</p>
                        <h3 className='font-bold mt-8'>Insurance</h3>
                        <p>The COMPANY does not extend coverage under any of its policies or products to Independent Distributors. If you use your personal property (such as your car or computer, home, etc.) for business use, such property may not be covered for loss or damage.</p>
                        <h3 className='font-bold mt-8'>Recruiting</h3>
                        <p>Cross-line recruiting: An Independent Distributor may not solicit an individual or entity that has been previously sponsored by another MAVIE Independent Distributor (or that is considering joining The COMPANY and being sponsored by another Independent Distributors) to join their MAVIE business as their direct enrollee.</p>
                        <p>The Independent Distributor may not solicit an MAVIE Independent Distributor or entity to join another network marketing opportunity offered by another company during the term of their MAVIE Independent Distributorship and for a period of one year after unless it is partially owned or officially associated with MAVIE. Violation of this company policy may result in immediate termination and revocation of any commissions earned!</p>
                        <h3 className='font-bold mt-8'>Independent Distributor Eligibility</h3>
                        <p>By entering into this agreement you represent and warrant that you: (a) are of legal age under your local law and at least 18 years old (applicable for natural persons); (b) you have full power and authority to enter into this agreement and (c) your MAVIE account have not been previously suspended or removed.</p>
                        <p>Our Platform is not directed or allowed to any person in any jurisdiction where (by reason of that person&apos;s nationality, residence or otherwise) the availability of the Platform is or may be prohibited. Due to legal restrictions and/or our business discretion you are not allowed to access our Platform if you are located in, under the control of, resident, habitant or citizen of the countries not listed within the Territory (see definition above) or if you are a resident, citizen or if you are located in any other jurisdiction in which applicable laws prohibit you to access our Platform (&ldquo;Restricted Use Areas&rdquo;).</p>
                        <p>MAVIE explicitly prohibits persons or entities in restricted use areas to use its Platform and MAVIE shall not be held liable for any legal or monetary consequence arising of such use. By accessing or using our Platform you represent and warrant that your activities are lawful in every jurisdiction where you access our Platform. Please note that restricted use areas may change in the future.</p>
                        <p>As a Independent Distributor, you confirm that you are fully familiar with the local law and restrictions where you carry out your marketing activities. As a business entity, you are obliged to familiarize yourself with the legislation where you operate and check whether the sale of products is permitted under local law, as well as whether the method of direct sale used by MAVIE is permitted. MAVIE expressly prohibits its business partners from engaging in any marketing activity that is inconsistent with local law. In the event of any breach of local regulations by Independent Distributor, MAVIE may terminate the business relationship with immediate effect, thereby terminating all MAVIE&apos;s obligations to the Independent Distributor.</p>
                        <p>You can become an Independent Distributor and register into the Back Office without buying a product, so without any payment and completely free.</p>
                        <h3 className='font-bold mt-8'>Cash or Monetary Incentives</h3>
                        <p>The COMPANY strictly prohibits Independent Distributors from offering cash or monetary incentives, promotions, prizes or bonuses to members of their downline or upline organizational members, or customers as a method of influencing customer acquisition.</p>
                        <p>To eliminate cross-line recruiting practices, the COMPANY strictly prohibits the use of cash or monetary incentives/promotions/prizes/bonuses for purposes of recruiting new Independent Distributors.</p>
                        <p>The COMPANY has put in place a specific sales model and strongly encourages its Independent Distributors to promote customer acquisition and recruiting by adhering to this sales model.</p>
                        <p>Territorial Rights/Conducting Business Across International Borders</p>
                        <p>Independent Distributors can market services and products and sponsor new Independent Distributors in any country in the Territory, where the COMPANY conducts business, without exclusivity. Independent Distributors may only promote the COMPANY in countries where the COMPANY currently operates.</p>
                        <p>Independent Distributors conducting business in foreign countries must adhere to the COMPANY Policies and Procedures governing activities in that country.</p>
                        <p>Independent Distributors are responsible for knowing and adhering to all laws and accepted business practices in the countries they choose to market. This includes but is not limited to customs and immigration laws and accepted marketing practices.</p>
                        <h3 className='font-bold mt-8'>License</h3>
                        <p>Subject to the terms and conditions of this Agreement, MAVIE grants to Independent Distributor, and Independent Distributor accepts, a non-exclusive, royalty-free, limited and non-transferable license, (&ldquo;License&rdquo;), pursuant hereto, to (i) advertise, promote, market, demonstrate and offer to sell the Products via the referral link in the Territory, during the term hereof, only for Independent Distributor&rsquo;s performance of this Agreement.</p>
                        <p>Restrictions Notwithstanding anything to the contrary in this Agreement, the License is subject to the following conditions:</p>
                        <p>Independent Distributor shall not sublicense the License,</p>
                        <p>the validity of the license is limited to the period of validity of the contractual relationship under these Agreement,</p>
                        <p>the license shall cease with immediate effect if Independent Distributor carries out marketing activities in a country where the sale of MAVIE products or the method of direct sale / multi-level marketing is not permitted by local law.</p>
                        <h3 className='font-bold mt-8'>Ranks of Independent Distributors</h3>
                        <p>You will be required to register for an account in order to become Independent Distributor. When you provide information during the registration process, you agree to provide only true, accurate, current and complete information and to update it as necessary to maintain its truth and accuracy. There are three ranks of Independent Distributors with different benefits.</p>
                        <p>You are only allowed to create one registration account and MAVIE shall block multiple accounts of the same user.</p>
                        <p>When registering and obtaining your MAVIE account, you will be required to complete the KYC Process. Completion of the KYC Process and identification of the Independent Distributor is a prerequisite for becoming the Ambassador or a Partner.</p>
                        <p>If you register for a MAVIE account, you agree to accept responsibility for all activities that occur under your account or password, if any, and you agree you will not sell, transfer or assign your subscription or any subscriber rights. You are responsible for maintaining the confidentiality of your password, if any, and for restricting access to your computer (or other Internet access device, as applicable) so that others may not access the password protected portion of the MAVIE using your account information in whole or in part. MAVIE reserves the right to terminate your account or otherwise deny you access in its sole discretion without notice and without liability.</p>
                        <p className='mt-4 underline'>There are different types of Independent Distributors:</p>
                        <p>Please get acquainted with our Compensation Plan Booklet, where all details are explained.</p>
                        <h3 className='font-bold mt-8'>Payment and Invoicing</h3>
                        <p>The COMPANY accepts payments exclusively in the cryptocurrency Tether USDT, via BEP 20 or TRC 20 protocols. Payment must be made from your personal wallet! Payments performed from cryptocurrency exchange accounts or other similar forms are not allowed.</p>
                        <p>Under no circumstances should you attempt to make any transactions to us in a digital currency in any form that we do not support. We assume no responsibility or liability in connection with any attempt to use digital currencies that we do not support. You acknowledge and agree that MAVIE bears no responsibility and is not liable for any unsupported asset that is sent to a wallet associated with your MAVIE Account.</p>
                        <p>All other forms of payment are prohibited. We will never ask you to pay in cash, FIAT currency or other cryptocurrencies. Payments made in another form or with another cryptocurrency will be rejected. We expressly point out that payments made in violation of these general terms and conditions do not create any obligations for the company!</p>
                        <p>When making payments, you are responsible for transferring funds to the correct address. The company is not responsible for any loss of USDT funds as a result of errors in the execution of the transfer from your part.</p>
                        <p>Payments in USDT performed in violation of this general rules and conditions will be automatically transferred to a separate account, where they will be processed manually by the company. The Company takes no responsibility or liability in connection to such incorrect payments and does not guarantee that such transferred funds will be returned. If, in accordance with these general conditions, it will be possible to determine from whom and from where the funds originated, the funds in USDT will be returned. The cost of processing irregular payments of USDT funds is 20 USDT. Surplus funds will not be returned.</p>
                        <p>Payments made in violation of these General Terms and Conditions will be as far as possible, returned in due time to the address from which they were sent. We are not responsible for any loss of funds and do not accept any responsibility for damage, either directly or indirectly due to payments performed contrary to this terms and conditions, such as: (i) received transfers in the wrong cryptocurrency, (ii) received transfers that is lower than the amount of the selected product, (iii) received transfers contrary to anti-money laundering policy, (iv) all payments received from cryptocurrency exchange or other addresses other than your personal wallet.</p>
                        <p>Incomplete transfers of digital funds that will be received by the Company&apos;s wallet, or transfers of digital funds that will be made in violation of these general terms and conditions, will be rejected. Such payments made in violation of these General Terms and Conditions will be automatically transferred to a separate account, where they will be processed manually by the staff. The Company takes no responsibility or liability in connection to such incorrect payments and does not guarantee that such transferred funds will be returned. Payment processing bears costs in the amount of 20 USDT. Possible overpayments under 20 USDT will not be refunded.</p>
                        <p>For users who want to exchange funds in USDT we suggest they do so on any exchange that supports USDTs. MAVIE does not provide fiat currency or other cryptocurrency exchange services. We allow our users the opportunity to cooperate with itez.com (DataBridge O&Uuml;), for which we do not guarantee or assume any responsibility. Each user must check third parties whose service they will use in the event of a change of another currency to the cryptocurrency USDT. We have no control over, or liability for, the delivery, quality, safety, legality or any other aspect of any goods or services that you may purchase or receive from, or sell or transfer to, any third party (including itez.com). We are not responsible for ensuring that a third party buyer or a seller you transact with, will complete the transaction or is authorised to do so. If you experience a problem with any goods or services purchased from, or sold to, any third party using its services, or if you have a dispute with such a third party, you should resolve the dispute directly with that third party.</p>
                        <p>The COMPANY offers a variety of different ways that allows the Independent Distributor to earn income through its Compensation Plan Booklet. Some of these payment plans require that the Independent Distributor be Qualified. Qualification requirements are defined in the Compensation Plan Booklet. It is the responsibility of the Independent Distributor to continually check to make sure that they are qualified for each individual pay plan that requires qualifications. The COMPANY will not be obligated to pay for any pay plan when an Independent Distributor falls out of qualification.</p>
                        <p>Payments of Independent Distributors is in detail described in a Booklet. MAVIE reserves the right to amend the Booklet in compliance with this business strategies and the development of the MAVIE business platform.</p>
                        <p>Independent Distributors entitled to direct payments are to be able to issue an invoice for their service. Until an invoice is issued by the Independent Distributor, the payment will not be sent. You will be required to register for an account in order to become Independent Distributor. When you provide information during the registration process, you agree to provide only true, accurate, current and complete information and to update it as necessary to maintain its truth and accuracy.</p>
                        <p>Independent Distributor acknowledges and agrees that he is an economic operator engaged in sales and distribution activities on the market, therefore the relationship with MAVIE is a commercial transaction and any rules of consumer law do not apply. In accordance with this terms and conditions, no Independent Distributor has the right to withdraw or request a refund on the basis of a distance or off-premises contract within 14 days, or under other provisions of consumer law. All products available are supply of goods or services for which the price is dependent on fluctuations in the market which cannot be controlled and which may occur within the withdrawal period, also all products are a supply of digital content which is not supplied on a tangible medium, where the performance has begun with the prior Independent Distributor express consent and his acknowledgment that he thereby loses his right of withdrawal.</p>
                        <p>You agree and understand that any payments in cryptocurrencies or otherwise for services or items sold by MAVIE or with the help of MAVIE marketing structure are irrevocable, undisputable and may not be charged back, contested or challenged now or in the future, doing so is a material breach of this terms and conditions for which MAVIE would be entitled to attorney fees, costs and fees associated with addressing a chargeback in addition to the amount challenged.</p>
                        <h3 className='font-bold mt-8'>Monthly Activity</h3>
                        <p>&quot;Monthly activity&quot; is the active or negative status of the Independent Distributor in the Back Office, which confirms that the Independent Distributor meets all the conditions to be eligible to all entitlements from MAVIE, including entitlements set in the Booklet. Monthly Activity does not affect rights already acquired; it only affects future entitlements. In case of negative Monthly Activity, the Independent Distributor does not acquire entitlements arising from the Booklet plan or other rights provided by MAVIE. The Independent Distributor can reactivate the Monthly Activity at any time by fulfilling the required conditions set by MAVIE. The terms of the Monthly Activity are specified on the page <Link href='https://www.backoffice.mavie.global' className='underline'>https://www.backoffice.mavie.global</Link>, and may be amended from time to time.</p>
                        <h3 className='font-bold mt-8'>Tax</h3>
                        <p>Each party shall report, pay and be liable for all of its own respective taxes. All monetary and non-monetary liabilities of MAVIE in this and other documents are specified in the gross amount.</p>
                        <h3 className='font-bold mt-8'>Marketing Advertising Policy</h3>
                        <p>MAVIE offers a variety of different promo materials that are provided by the company to help you build your business. There are those Independent Distributors who prefer to use their own materials or create materials for certain special events. In the event that this is the case, we have outlined our policy and procedures for personalized marketing materials in mandatory MAVIE Marketing Guidelines. The use of marketing materials, displays, advertisements or other marketing resources not published by the MAVIE is not permitted without prior written consent.</p>
                        <p>MAVIE requires that all personalized marketing material be approved, in writing by the COMPANY before an Independent Distributor can DISTRIBUTE such material. Any request from an Independent Distributor must be in writing and include the following:</p>
                        <ul className='list-disc ml-6'>
                            <li>Independent Distributor Name</li>
                            <li>Independent Distributor ID Number</li>
                            <li>Address and telephone number</li>
                            <li>The complete copy or material that you wish to submit</li>
                            <li>When you will use the material</li>
                            <li>Where it will be distributed</li>
                            <li>How you will distribute the material&nbsp;</li>
                        </ul>
                        <p>Once the materials are received, please allow 15 to 21 business days for processing. If you have not received a response in this time, please email us back at support@mavie.global.</p>
                        <p className='pt-4'>Under no circumstances may an Independent Distributor place an ad to promote the COMPANY&rsquo;s Products and/or Compensation Plan in a national publication without prior, written approval from the COMPANY.</p>
                        <h3 className='font-bold mt-8'>General Rules</h3>
                        <p>Always introduce and refer to yourself as an Independent Distributor. You must never give the impression that you represent the COMPANY in any way as an employee or official agent.</p>
                        <p>The use of MAVIE&rsquo;s logos and trademarks or service marks is strictly forbidden without prior, written approval from the COMPANY.</p>
                        <p>Make sure that when you design the material, it clearly shows that it is coming from you as an Independent Distributor and not produced by MAVIE in any way shape or form.</p>
                        <p>You may use COMPANY written information that is commonly found in our current marketing materials but may not do so word for word without prior, written approval from the COMPANY as our materials are protected by copyright laws .</p>
                        <p>You must never make any promises of income.</p>
                        <p>You are prohibited from using the words, &ldquo;investment,&rdquo; &ldquo;savings&rdquo;, &ldquo;guaranteed return&rdquo;, &ldquo;yields&rdquo;, &ldquo;capital gains&rdquo;, &ldquo;profit&rdquo; or any word or phrase that implies cash and investment returns to any of our products, or choose these words as part of your MAVIE username, or choose them as part of your replicated marketing materials or any other website or website address associated with our products or brands or trademarks.</p>
                        <h3 className='font-bold mt-8'>The Promotion of International Expansion</h3>
                        <p>MAVIE has plans to enter into the international market by marketing our products into other countries. It is important to point out that every country has its own established rules and regulations that companies must follow in order to market their products. The process can be very precise. It is therefore important that all Independent Distributors of MAVIE refrain completely from trying to market our product in other countries out of &ldquo;Territory&rdquo; at this time. MAVIE will announce to our Independent Distributors as we receive individual approvals to market our products, one country at a time. Upon those announcements, Independent Distributors will then be allowed to market our product in those countries. In keeping with this policy, Independent Distributors must:</p>
                        <p>&bull; Not market our product or opportunity in a country that is not approved by MAVIE.</p>
                        <p>&bull; Not market in any form to prospects in a country that is not approved by MAVIE.</p>
                        <p>When developing personal marketing materials for any country that is approved by MAVIE, please refer to the appropriate guidelines the COMPANY sets forth for that particular country.</p>
                        <p>It is not permitted to translate Promo Materials in any other language than provided by MAVIE (most often in English), unless MAVIE expressly and in writing confirms the translation. In case of conflict between the Promo Materials provided by MAVIE and the translated Promo Materials, the MAVIE&rsquo;s original version of Promo Materials is valid and shall be given precedence.</p>
                        <h3 className='font-bold mt-8'>Direct Mail Pieces, Fliers and Brochures</h3>
                        <p>Independent Distributors will not be allowed to substitute their names on any materials that have been previously approved for other Independent Distributors.</p>
                        <p>Photocopying of any marketing materials provided by MAVIE is not permissible, however, Independent Distributors may print any current material that is provided by the company on our website.</p>
                        <h3 className='font-bold mt-8'>Spamming</h3>
                        <p>MAVIE, does not permit Independent Distributors to send unsolicited e-mails. Any e-mail sent by an Independent Distributors that promotes MAVIE, the MAVIE opportunity, or MAVIE products and services must comply with the following:</p>
                        <p>There must be a functioning return e-mail address to the sender that includes a request that future e-mail solicitations or correspondence not be sent to him or her (a functioning &ldquo;opt-out&rdquo; notice).</p>
                        <p>The use of deceptive subject lines and/or false header information is prohibited.</p>
                        <p>All opt-out requests, whether received by e-mail or regular mail, must be honored.</p>
                        <p>All emails sent that promote MAVIE, its opportunity or products, must adhere to all the other marketing and advertising guidelines in this policy.</p>
                        <h3 className='font-bold mt-8'>Trademarks and Copyrights</h3>
                        <p><span>The COMPANY will not allow the use of its trade names, trademarks, designs, photos, videos, audio recordings or symbols by any person, including a COMPANY Independent Distributor, without its prior, written permission. Independent Distributors may not produce for sale or distribution any recorded company events and speeches without written permission from the COMPANY; nor may Independent Distributors reproduce for sale or for personal use any recording of company-produced audio or video tape presentations.</span></p>
                        <h3 className='font-bold mt-8'>Media and Media Inquiries</h3>
                        <p><span>Independent Distributors must not attempt to respond to media inquiries regarding the COMPANY, its products or their independent business. All inquiries by any type of media must be immediately referred to COMPANY. This policy is designed to assure that accurate and consistent information is provided to the public as well as a proper public image.</span></p>
                        <h3 className='font-bold mt-8'>Events</h3>
                        <p>The COMPANY supports the practice of Regional and local Training Events, &quot;Personal Business Opportunity Meetings&rdquo; and Private Business Receptions, as they are valuable educational tools when held properly with both professionalism and integrity. Under no circumstances are any type of meeting/training session intended to provide any additional income stream to those who are sponsoring the events, and must be offered as non-profit activities at all times.</p>
                        <p>All Regionals, private marketing events, or on-line webinars must be submitted to the COMPANY for approval in conjunction with the current terms of hosting such events. Events that do not receive prior approval will be considered operating outside of the COMPANY&rsquo;s approval and philosophy and will not be promoted or endorsed by the company in any manner.</p>
                        <p>Attendance at COMPANY events is not a requirement for being an Independent Distributor, nor a prerequisite for success in this business.</p>
                        <h3 className='font-bold mt-8'>Remuneration</h3>
                        <p><span>The COMPANY reserves the right to pursue the remuneration of any legal or operational fees or the recovery for any damages as a result of any policy violation by the COMPANY Independent Distributors. The COMPANY also reserves the right to recoup such costs from future bonuses, commissions or other payments.</span></p>
                        <h3 className='font-bold mt-8'>Further Limitations</h3>
                        <p><span>The COMPANY reserves the right to limit or disallow any marketing activities that cast negative aspersions on the integrity, truthfulness, and/or reputation of the COMPANY.</span></p>
                        <h3 className='font-bold mt-8'>Transfer/Disposition of Independent Distributors Business</h3>
                        <p>An Independent Distributor&rsquo;s position can be inherited or bequeathed, but cannot be transferred or assigned during his or her lifetime without written consent of the COMPANY. The transfer of a position is an exception and is generally allowed in special cases due to medical, social or other objective inability to continue performing the activity of an ID.</p>
                        <p>Upon the death or incapacity of an Independent Distributor, or of its principals, the rights to the commission and marketing position shall pass to the designated successor, provided said successor complies with all the terms of the COMPANY agreement, the COMPANY&rsquo;s Policies and Procedures and fulfills the duties and obligations required of an Independent Distributor. In the case of a transfer to an existing Independent Distributor, or to an individual listed as a partner/shareholder/trustee in an existing Independent Distributor status, the individual will need to contact The COMPANY to discuss his/her options in either maintaining the status or transferring it. If the transfer is of a temporary nature (i.e. the Independent Distributor is temporarily incapacitated), the subsequent activation and deactivation will likewise be temporary.</p>
                        <h3 className='font-bold mt-8'>Miscellaneous Provisions</h3>
                        <p>MAVIE reserves the right to assign this Agreement, in whole or in part, on written notice. MAVIE is also permitted to assign its rights to payments without obtaining your consent. It is not considered an assignment for MAVIE to divest a portion of its business in a manner that similarly affects all of its Companies.Your rights under this Agreement are not property rights and, therefore, you can not transfer them to another party or encumber them in any way. For example, you can not sell your approval to market MAVIE&rsquo;s Products or Services or your rights to use MAVIE&rsquo;s Trademarks. You agree not to assign or otherwise transfer this Agreement, your rights under this Agreement, or any of its approvals, or delegate any duties, unless expressly permitted to do so in this Agreement. Otherwise, any attempt to do so is void.</p>
                        <p>Both parties agree to the application of the Laws of British Virgin Islands to govern, interpret, and enforce all of your and MAVIE&rsquo;s respective rights, duties and obligations arising from, or relating, in any manner to, the subject matter of this Agreement, without regard to conflict of law principles. If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions of the Agreement remain in full force and effect.</p>
                        <p>This Agreement sets forth the entire understanding of the parties and supersedes any and all written or verbal agreements between the parties related to the subject matter hereof. Any amendment to this Agreement must be in writing signed by a duly authorized officer or representative of the parties.</p>
                        <p>Any notice required or permitted by this Agreement shall be in writing and shall be sent to support@mavie.global.</p>
                        <p>The relationship of the parties shall at all times be one between independent contractors, and neither party shall be, nor represent itself to be, an employee, agent, representative or joint venture Independent Distributor of the other, nor shall either party have the right or authority to assume or create any obligation on behalf of, or in the name of, the other or otherwise to act on behalf of the other.</p>
                        <p>The terms and conditions of Orders and any other commercial transactions, if any, between MAVIE and Customers are separate and independent of any agreements between Independent Distributor and MAVIE. Independent Distributor has no authority than is expressly granted by this Agreement. Without limiting the foregoing, Independent Distributor has no authority to make any warranties or refunds.</p>
                        <p>All communications, written (including but not limited to e-mail), and oral, will be in English. If any party desires to translate, the cost of such will be on the party which desires the translation.</p>
                        <p className='font-[100] my-4'>Exclusivity</p>
                        <p>MAVIE is free to advertise, promote, market, demonstrate, offer to sell, sell and license Products in or outside the Territory to any third party, including Customers and customers of Independent Distributor, through itself or with the assistance of any third party. MAVIE is free to enter into the same terms and conditions or similar terms and conditions as this Agreement with any person or entity for any customers, including but not limited to Customer(s) in or outside the Territory.</p>
                        <p>Independent Distributor is not allowed to sell, advertise, promote, market, demonstrate, offer to sell and license any products that are not MAVIE&rsquo;s Products to Customers and Independent Distributor&rsquo;s customers that were found through or because of MAVIE.</p>
                        <h3 className='font-bold mt-8'>Privacy Policy</h3>
                        <p>The COMPANY maintains a strong commitment to protecting the privacy of our customers and Independent Distributors and their personal information. &ldquo;Personal Information&rdquo; means any information about an identifiable individual, other than business contact information. We protect that information. Unauthorized disclosure or access of personal information, including but not limited to account information or personal identification number, is a violation of the COMPANY&rsquo;s Privacy Policy, and is strictly prohibited.</p>
                        <p>Please read our Privacy Policy on the following link &ndash; Privacy Policy.</p>
                        <h3 className='font-bold mt-8'>Conclusion</h3>
                        <p>The rules and regulations outlined in this document are intended to protect the MAVIE opportunity for all involved. Please follow the Terms and Conditions as well as the Policies and Procedures as set forth here to insure that you are in compliance.</p>
                        <p>Please note that any infraction of these rules and regulations may result in suspension or immediate deactivation/termination of your status as an MAVIE Independent Distributor. It is the goal of the COMPANY to introduce our products to as many retail customers as possible with the purpose in mind of offering them a logical alternative. Coupled with this is our desire to help others achieve financial reward for being involved with us as an Independent Distributor. The COMPANY desires to develop a long term, stable relationship of mutual respect, trust and integrity with our Independent Distributors. By assisting our Independent Distributors in achieving their goals and dreams, the COMPANY&rsquo;s goal of establishing a long lasting team will be realized.</p>
                    </div>
                </section>
            </TextContainer>
        </MainLayout>
    )
}

export default Terms
